export const DATA = [
    {
        id: "freeYoutubeCourses1",
        sectionsHeading: "Linux Courses",
        topLine: 'Free Courses',
        YTChannelImageLink: "https://i.ytimg.com/vi/U1w4T03B30I/maxresdefault.jpg",
        tag: 'Linux',
        videoHeading: 'Linux for Ethical Hackers',
        videoLink: "https://youtu.be/U1w4T03B30I",
        channelName: "The Cyber Mentor",
        channelLogo: "https://yt3.ggpht.com/ytc/AKedOLRGnc0be-YXi3zenYi6s8uwgPxi_IrLBZ7Rigv7=s48-c-k-c0x00ffffff-no-rj",
        timeStamp: "Oct 7 2022",
        alt: 'Linux Courses',
        channelLink: "https://www.youtube.com/c/TheCyberMentor",
    },
    {
        id: "freeYoutubeCourses2",
        sectionsHeading: "Linux Courses",
        topLine: 'Free Courses',
        YTChannelImageLink: "https://i.ytimg.com/vi/T0Db6dVYyoA/maxresdefault.jpg",
        tag: 'Linux',
        videoHeading: 'Linux Essentials For Hackers',
        videoLink: "https://www.youtube.com/watch?v=T0Db6dVYyoA&list=PLBf0hzazHTGMh2fe2MFf3lCgk0rKmS2by",
        channelName: "HackerSploit",
        channelLogo: "https://yt3.ggpht.com/ytc/AMLnZu9nSdhYbPUgxIavX6vicAOFioLHhkuCNeHcp-Icpw=s48-c-k-c0x00ffffff-no-rj",
        timeStamp: "Oct 7 2022",
        alt: 'Linux Courses',
        channelLink: "https://www.youtube.com/c/HackerSploit",
    },
    {
        id: "freeYoutubeCourses3",
        sectionsHeading: "Linux Courses",
        topLine: 'Free Courses',
        YTChannelImageLink: "https://i.ytimg.com/vi/T0Db6dVYyoA/maxresdefault.jpg",
        tag: 'Linux',
        videoHeading: 'Linux Essentials For Hackers',
        videoLink: "https://www.youtube.com/watch?v=T0Db6dVYyoA&list=PLBf0hzazHTGMh2fe2MFf3lCgk0rKmS2by",
        channelName: "HackerSploit",
        channelLogo: "https://yt3.ggpht.com/ytc/AMLnZu9nSdhYbPUgxIavX6vicAOFioLHhkuCNeHcp-Icpw=s48-c-k-c0x00ffffff-no-rj",
        timeStamp: "Oct 7 2022",
        alt: 'Linux Courses',
        channelLink: "https://www.youtube.com/c/HackerSploit",
    },
    {
        id: "freeYoutubeCourses4",
        sectionsHeading: "Blue Team Courses",
        topLine: "Free Courses",
        YTChannelImageLink: "https://i.ytimg.com/vi/Bt5fh3wQUAQ/maxresdefault.jpg",
        tag: "Blue Team",
        videoHeading: "Blue Team Tutorials",
        videoLink: "https://www.youtube.com/watch?v=Bt5fh3wQUAQ&list=PLBf0hzazHTGNcIS_dHjM2NgNUFMW1EZFx",
        channelName: "HackerSploit",
        channelLogo: "https://yt3.ggpht.com/ytc/AMLnZu9nSdhYbPUgxIavX6vicAOFioLHhkuCNeHcp-Icpw=s48-c-k-c0x00ffffff-no-rj",
        timeStamp: "Oct 7 2022",
        alt: "Blue Team Courses",
        channelLink: "https://www.youtube.com/c/HackerSploit",
    },
    {
    id: "freeYoutubeCourses5",
    sectionsHeading: "Bug hunting Courses",
    topLine: "Free Courses",
    YTChannelImageLink: "https://i.ytimg.com/vi/Rp69edBmFFo/maxresdefault.jpg",
    tag: "Bug Hunting",
    videoHeading: "Beginner to Advanced Bug Bounty Hunting Course",
    videoLink: "https://youtu.be/hDYqWZ11njU?list=PLbyncTkpno5FAC0DJYuJrEqHSMdudEffw",
    channelName: "PhD Security",
    channelLogo:
    "https://yt3.ggpht.com/1TEM6wyKF82rwwcPYTQIHD_OeVxH02kYWBpzqc7J3OerSrQZmgMTrtYRVi35arnfh9a3GYDv=s68-c-k-c0x00ffffff-no-rj",
    timeStamp: "Oct 7 2022",
    alt: "Bug hunting Courses",
    channelLink: "https://www.youtube.com/channel/UCAndnmvdiphDqLLDrGnBuhA",
},
{
    id: "freeYoutubeCourses6",
        sectionsHeading: "Bug hunting Courses",
            topLine: "Free Courses",
                YTChannelImageLink: "https://i.ytimg.com/vi/hDYqWZ11njU/maxresdefault.jpg",
                    tag: "Bug Hunting",
                        videoHeading: "How to Get Started with Bug Bounty - Resource Lists & Advice",
                            videoLink: "https://youtu.be/hDYqWZ11njU?list=PLbyncTkpno5FAC0DJYuJrEqHSMdudEffw",
                                channelName: "InsiderPhD",
                                    channelLogo: "https://yt3.ggpht.com/ytc/AMLnZu9FToR3EOEIhCjUcq70BroVP_aoBYtlnC-Ncst7=s48-c-k-c0x00ffffff-no-rj",
                                        timeStamp: "Oct 7 2022",
                                            alt: "Bug hunting Courses",
                                                channelLink: "https://www.youtube.com/c/InsiderPhD",
        },
{
    id: "freeYoutubeCourses7",
        sectionsHeading: "Bug hunting Courses",
            topLine: "Free Courses",
                YTChannelImageLink: "https://i.ytimg.com/vi/7SfXpXAMiHw/maxresdefault.jpg",
                    tag: "Bug Hunting",
                        videoHeading: "Guide to Failing at Bug Bounties - Naive Recon",
                            videoLink: "https://www.youtube.com/watch?v=7SfXpXAMiHw&list=PLhfP6zOcRP1f_FyWc_gk1fRz1mxst0QE5",
                                channelName: "RogueSMG",
                                    channelLogo: "https://yt3.ggpht.com/ytc/AMLnZu-TT8JmxUj6Ojd1HiblwtJlCpt2zuDRziY4OA0L=s88-c-k-c0x00ffffff-no-rj",
                                        timeStamp: "Oct 7 2022",
                                            alt: "Bug hunting Courses",
                                                channelLink: "https://www.youtube.com/c/RogueSMG",
        },
{
    id: "freeYoutubeCourses8",
        sectionsHeading: "Bug hunting Courses",
            topLine: "Free Courses",
                YTChannelImageLink: "https://i.ytimg.com/vi/VC_JYH45s74/maxresdefault.jpg",
                    tag: "Bug Hunting",
                        videoHeading: "Guide to Failing at Bug Bounties - Naive Recon",
                            videoLink: "https://www.youtube.com/watch?v=VC_JYH45s74&list=PLhfP6zOcRP1fXtBtxhTlu9KR-PKDA6biX",
                                channelName: "RogueSMG",
                                    channelLogo: "https://yt3.ggpht.com/ytc/AMLnZu-TT8JmxUj6Ojd1HiblwtJlCpt2zuDRziY4OA0L=s88-c-k-c0x00ffffff-no-rj",
                                        timeStamp: "Oct 7 2022",
                                            alt: "Bug hunting Courses",
                                                channelLink: "https://www.youtube.com/c/RogueSMG",
        },
{
    id: "freeYoutubeCourses9",
        sectionsHeading: "Bug hunting Courses",
            topLine: "Free Courses",
                YTChannelImageLink: "https://i.ytimg.com/vi/CAGMC-AfR1o/maxresdefault.jpg",
                    tag: "Bug Hunting",
                        videoHeading: "No BS Guides",
                            videoDescription:
    "This is my gift for you the ultimate getting started guide for bug bounties / ethical hacking / cybersecurity. In this video, I go through a ton of resources including books, courses, videos, podcasts, conferences, and give out some study guides for people who wanna get into bug bounties but they have no hacking experience, no experience in tech, some security experience but not in bug bounties. I hope you find this super useful, it's PACKED full of information, almost an hour of stuff to check out!.",
        videoLink: "https://www.youtube.com/watch?v=CAGMC-AfR1o&list=PLhfP6zOcRP1dCTjbENt4ilFKFwFpspOoS",
            channelName: "RogueSMG",
                channelLogo: "https://yt3.ggpht.com/ytc/AMLnZu-TT8JmxUj6Ojd1HiblwtJlCpt2zuDRziY4OA0L=s88-c-k-c0x00ffffff-no-rj",
                    timeStamp: "Oct 7 2022",
                        alt: "Bug hunting Courses",
                            channelLink: "https://www.youtube.com/c/RogueSMG",
        },
        {
        id: "freeYoutubeCourses10",
    sectionsHeading: "Penetration Testing courses",
    topLine: "Free Courses",
    YTChannelImageLink: "https://i.ytimg.com/vi/qJ9ZmkMvkcA/maxresdefault.jpg",
    tag: "Cyber Security",
    videoHeading: " Penetration Testing Bootcamp - Introduction",
    videoDescription:
      "In this video, I explore the various cybersecurity paths available as well as their corresponding certifications and skills required in order to transition into a cybersecurity role/career.",
    videoLink: "https://www.youtube.com/watch?v=qJ9ZmkMvkcA&list=PLBf0hzazHTGOepimcP15eS6Y-aR4m6ql3",
    channelName: "HackerSploit",
    channelLogo: "https://yt3.ggpht.com/ytc/AMLnZu9nSdhYbPUgxIavX6vicAOFioLHhkuCNeHcp-Icpw=s48-c-k-c0x00ffffff-no-rj",
    timeStamp: "Oct 7 2022",
    alt: "Red Team Courses",
    channelLink: "https://www.youtube.com/c/HackerSploit",
  },
  {
    id: "freeYoutubeCourses11",
    sectionsHeading: "Penetration Testing courses",
    topLine: "Free Courses",
    YTChannelImageLink: "https://i.ytimg.com/vi/fNzpcB7ODxQ/maxresdefault.jpg",
    tag: "Cyber Security",
    videoHeading: "Ethical Hacking in 12 Hours - Full Course - Learn to Hack!",
    videoDescription:
      "In this video, I explore the various cybersecurity paths available as well as their corresponding certifications and skills required in order to transition into a cybersecurity role/career.",
    videoLink: "https://youtu.be/fNzpcB7ODxQ",
    channelName: "The Cyber Mentor",
    channelLogo: "https://yt3.ggpht.com/ytc/AKedOLRGnc0be-YXi3zenYi6s8uwgPxi_IrLBZ7Rigv7=s48-c-k-c0x00ffffff-no-rj",
    timeStamp: "Oct 7 2022",
    alt: "ResourcesSvg",
    channelLink: "https://www.youtube.com/c/TheCyberMentor",
  },
  {
    id: "freeYoutubeCourses12",
    sectionsHeading: "Red Team Courses",
    topLine: "Free Courses",
    YTChannelImageLink: "https://i.ytimg.com/vi/EIHLXWnK1Dw/maxresdefault.jpg",
    tag: "Red Team",
    videoHeading: "Red Team Tutorials",
    videoLink: "https://www.youtube.com/watch?v=EIHLXWnK1Dw&list=PLBf0hzazHTGMjSlPmJ73Cydh9vCqxukCu",
    channelName: "HackerSploit",
    channelLogo: "https://yt3.ggpht.com/ytc/AMLnZu9nSdhYbPUgxIavX6vicAOFioLHhkuCNeHcp-Icpw=s48-c-k-c0x00ffffff-no-rj",
    timeStamp: "Oct 7 2022",
    alt: "Red Team Courses",
    channelLink: "https://www.youtube.com/c/HackerSploit",
  },
];


